### ISSUE TITLE
Question about refresh

### ISSUE THREAD

**Issue by Senach** [DaveGut/Cloud-Based_TP-Link-to-SmartThings-Integration#7]
Hi,

First, thank you for publishing this code.  It worked great and was easy to implement.  

I was wondering if the refresh rate could be changed from 5 min to 1 min or less.  I edited the code for my device handler but it did not seem to work.  I changed both places I could find refresh, rates and update.

Thank you

**Comment by DaveGut** [comment]
It can be changed.  Instructions below.  I use 5 minutes as a minimum since the primary purpose of the refresh is in case someone changes (turns on/off, change color, etc) from the Kasa App.  It is NOT required to maintain connectivity and the internet connection.  Any change invoked through SmartThings is almost instantaneously updated (and independent of the refresh cycle).

My question is what you are trying to accomplish.  There may be a better way and I can work with you to modify for all (or make recommendations if it seems reasonable).

To change, go to the method update (def update)).  At the end of this, add the line:

runEvery1Minute(refresh)

Then save, publish.  On the smart phone, go to preferences (the gear icon on the details page).  Select Save.  This will activate the run every.

Why not shorter periods?  I could use a runIn command.
   1.  runIn commands could be chained; however, if the method ever fails (for any reason), the command will not run again.
   2.  Each time you run refresh, a cloud command chain is invoked.  This is a burden to the Kasa cloud.  I am trying to keep us under the radar here.
   3.  The 1 minute refresh results in a 30 second average latency for non-induced changes.

**Comment by Senach** [comment]
I have a bathroom fan that runs x number of hours a day to bring in fresh air.  I created a smartlight app action that if the fan is turned off during the running hours the fan will turn back on.  This prevents a problem I have with a child and sometimes visiting adults turning the fan off during its daily runtime.  I tested it and it does take 5 min to turn the fan back on.  This is not terrible but thought there may be a way to have the refresh happen more frequent.  What do you think?  Is the one minute the best way to deal with this or do you think there would be a better way?  Thank you so much for this code, instructions, and further help!

Thanks,
Kelly

**Comment by DaveGut** [comment]
The only sure way is the runEvery1Minute.  Below is a file with the updated device handler to support 1 minute refresh.  Simply replace the text on the IDE, publish, and save.  Then in the smart app, go to the preferences page for the device and select the every minute option.


[Plug with fast refresh.groovy.txt](https://github.com/DaveGut/Cloud-Based_TP-Link-to-SmartThings-Integration/files/1764494/Plug.with.fast.refresh.groovy.txt)

**Comment by Senach** [comment]
Awesome, thank you for the help.  Yes, it is an HS200.
